import jaconv
import math
import os
import time
from abc import abstractmethod
from flask_mail import Message
from src import setting
from src.exception.custom_exception import custom_exception
from src.util.util import util
from src.model.entity.pre_users_entity import pre_users_entity
from src.model.entity.users_entity import users_entity
from src.model.entity.sexes_entity import sexes_entity
from src.model.entity.birth_days_entity import birth_days_entity
from src.model.entity.prefectures_entity import prefectures_entity
from src.model.entity.jobs_entity import jobs_entity
from src.model.entity.contact_methods_entity import contact_methods_entity
from src.model.entity.knew_triggers_entity import knew_triggers_entity
from src.model.entity.zip_addresses_entity import zip_addresses_entity
from src.model.entity.user_contact_methods_entity import user_contact_methods_entity
from src.model.entity.user_knew_triggers_entity import user_knew_triggers_entity
from src.model.repository.pre_users_repository import pre_users_repository
from src.model.repository.users_repository import users_repository
from src.model.repository.sexes_repository import sexes_repository
from src.model.repository.birth_days_repository import birth_days_repository
from src.model.repository.prefectures_repository import prefectures_repository
from src.model.repository.jobs_repository import jobs_repository
from src.model.repository.contact_methods_repository import contact_methods_repository
from src.model.repository.knew_triggers_repository import knew_triggers_repository
from src.model.repository.zip_addresses_repository import zip_addresses_repository
from src.model.repository.user_contact_methods_repository import user_contact_methods_repository
from src.model.repository.user_knew_triggers_repository import user_knew_triggers_repository
from src.controller.controller import controller
from src.controller.user_registration.user_registration_common_controller import user_registration_common_controller
