import collections
from sqlalchemy import text
from src import setting
from .repository import repository
from .birth_days_repository import birth_days_repository
from .contact_methods_repository import contact_methods_repository
from .jobs_repository import jobs_repository
from .knew_triggers_repository import knew_triggers_repository
from .pre_users_repository import pre_users_repository
from .prefectures_repository import prefectures_repository
from .sexes_repository import sexes_repository
from .user_contact_methods_repository import user_contact_methods_repository
from .user_knew_triggers_repository import user_knew_triggers_repository
from .users_repository import users_repository
from .zip_addresses_repository import zip_addresses_repository
