from src.model.entity.birth_days_entity import birth_days_entity
from src.model.entity.contact_methods_entity import contact_methods_entity
from src.model.entity.jobs_entity import jobs_entity
from src.model.entity.knew_triggers_entity import knew_triggers_entity
from src.model.entity.prefectures_entity import prefectures_entity
from src.model.entity.pre_users_entity import pre_users_entity
from src.model.entity.sexes_entity import sexes_entity
from src.model.entity.users_entity import users_entity
from src.model.entity.user_contact_methods_entity import user_contact_methods_entity
from src.model.entity.user_knew_triggers_entity import user_knew_triggers_entity
from src.model.entity.zip_addresses_entity import zip_addresses_entity
